// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartCourseAPI.Data;

#nullable disable

namespace SmartCourseAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartCourseAPI.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("EnrolledCount")
                        .HasColumnType("int");

                    b.Property<bool>("SeatsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "JavaScript Fundamentals",
                            Credits = 3,
                            DepartmentId = 1,
                            EnrolledCount = 0,
                            SeatsAvailable = true,
                            TotalSeats = 30
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "React & Redux",
                            Credits = 4,
                            DepartmentId = 4,
                            EnrolledCount = 0,
                            SeatsAvailable = true,
                            TotalSeats = 25
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "ASP.NET Core Web API",
                            Credits = 4,
                            DepartmentId = 4,
                            EnrolledCount = 0,
                            SeatsAvailable = true,
                            TotalSeats = 20
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "Python for Data Science",
                            Credits = 5,
                            DepartmentId = 2,
                            EnrolledCount = 0,
                            SeatsAvailable = true,
                            TotalSeats = 35
                        },
                        new
                        {
                            CourseId = 5,
                            CourseName = "Database Design & SQL",
                            Credits = 3,
                            DepartmentId = 1,
                            EnrolledCount = 0,
                            SeatsAvailable = true,
                            TotalSeats = 25
                        },
                        new
                        {
                            CourseId = 6,
                            CourseName = "Machine Learning Basics",
                            Credits = 5,
                            DepartmentId = 2,
                            EnrolledCount = 0,
                            SeatsAvailable = true,
                            TotalSeats = 30
                        },
                        new
                        {
                            CourseId = 7,
                            CourseName = "Network Security",
                            Credits = 4,
                            DepartmentId = 5,
                            EnrolledCount = 0,
                            SeatsAvailable = true,
                            TotalSeats = 20
                        },
                        new
                        {
                            CourseId = 8,
                            CourseName = "Cloud Computing & DevOps",
                            Credits = 4,
                            DepartmentId = 3,
                            EnrolledCount = 0,
                            SeatsAvailable = true,
                            TotalSeats = 25
                        });
                });

            modelBuilder.Entity("SmartCourseAPI.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Computer Science"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Data Science"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Information Technology"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Software Engineering"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Cybersecurity"
                        });
                });

            modelBuilder.Entity("SmartCourseAPI.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DropDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId", "IsActive");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("SmartCourseAPI.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "admin@smartcourse.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$Aam20HCcvhAJuRZVvFHm/uYkMFGsDPEeiSAxlaoTTTJOA2NVfyPAm",
                            Phone = "9000000000",
                            Role = "Admin"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "alice@smartcourse.com",
                            Name = "Alice Johnson",
                            PasswordHash = "$2a$11$mzLUjQg3jQyEEgnRD0oSYOoqo926M6.N8bCSI12tHUWveWWhkP8ee",
                            Phone = "9111111111",
                            Role = "Student"
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "bob@smartcourse.com",
                            Name = "Bob Smith",
                            PasswordHash = "$2a$11$mzLUjQg3jQyEEgnRD0oSYOoqo926M6.N8bCSI12tHUWveWWhkP8ee",
                            Phone = "9222222222",
                            Role = "Student"
                        },
                        new
                        {
                            StudentId = 4,
                            Email = "carol@smartcourse.com",
                            Name = "Carol White",
                            PasswordHash = "$2a$11$mzLUjQg3jQyEEgnRD0oSYOoqo926M6.N8bCSI12tHUWveWWhkP8ee",
                            Phone = "9333333333",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("SmartCourseAPI.Models.Course", b =>
                {
                    b.HasOne("SmartCourseAPI.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SmartCourseAPI.Models.Enrollment", b =>
                {
                    b.HasOne("SmartCourseAPI.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCourseAPI.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartCourseAPI.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SmartCourseAPI.Models.Department", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("SmartCourseAPI.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
